'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
type Session={id:string;locationId:string;status:string;version:number;openingCents:number;countCents:number|null;expectedCents:number|null;varianceCents:number|null;notes:string;reviewNotes:string|null;createdAt:string}
type Data={locations:{id:string;name:string}[];sessions:Session[];canApprove:boolean}
type Preview={session:Session;hash:string|null;snapshot:null|{openingCents:number;expectedCents:number;receipts:{key:string;reference:string;kind:string;amountCents:number;at:string}[];movements:{id:string;reason:string;amountCents:number;at:string}[]}}
const field='w-full rounded border border-gray-300 p-2',button='rounded bg-purple-700 px-4 py-2 text-white disabled:opacity-50',usd=(c:number|null)=>'$'+((c||0)/100).toFixed(2)
export default function CashDrawer(){
 const [data,setData]=useState<Data|null>(null),[preview,setPreview]=useState<Preview|null>(null),[location,setLocation]=useState(''),[opening,setOpening]=useState('0'),[notes,setNotes]=useState(''),[amount,setAmount]=useState(''),[direction,setDirection]=useState('OUT'),[count,setCount]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const retry=useRef<{body:string;key:string}|null>(null)
 const load=useCallback(async()=>{const r=await fetch('/api/operations/cash-drawer',{cache:'no-store'}),v=await r.json();if(!r.ok)throw Error(v.error||'Could not load drawers');setData(v)},[])
 useEffect(()=>{load().catch(e=>setError(e.message))},[load])
 async function inspect(id:string){const r=await fetch('/api/operations/cash-drawer?id='+encodeURIComponent(id),{cache:'no-store'}),v=await r.json();if(!r.ok)throw Error(v.error||'Could not load drawer');setPreview(v)}
 async function action(input:Record<string,unknown>){const body=JSON.stringify(input);if(retry.current?.body!==body)retry.current={body,key:crypto.randomUUID()};setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/operations/cash-drawer',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':retry.current.key},body}),v=await r.json();if(r.status<500)retry.current=null;if(!r.ok)throw Error(v.error||'Drawer action failed');await load();await inspect(input.action==='MOVEMENT'?String(input.id):v.id);setMessage('Saved. Review the current drawer status.');setNotes('');setAmount('');setCount('')}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 const active=data?.sessions.find(s=>s.locationId===location&&s.status!=='CLOSED')
 return <main className="mx-auto max-w-5xl space-y-6 p-6"><h1 className="text-3xl font-bold">Cash drawer & closeout</h1><p>Reconcile one shared USD cash drawer per location. Verified cash receipts and successful cash refunds are counted once. Record physical additions and withdrawals separately.</p>{error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-800">{error}</p>}{message&&<p role="status" className="rounded bg-green-50 p-3">{message}</p>}<button className={button} disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh drawers</button>
 {data&&<>
 <section className="space-y-3 rounded border bg-white p-5"><h2 className="text-xl font-semibold">Open a drawer</h2><label className="block">Location<select aria-label="Location" className={field} value={location} onChange={e=>{setLocation(e.target.value);const previous=data.sessions.find(s=>s.locationId===e.target.value&&s.status==='CLOSED');setOpening(((previous?.countCents||0)/100).toFixed(2))}}><option value="">Select a location</option>{data.locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="block">Opening cash USD<input className={field} type="number" step="0.01" min="0" max="1000000" value={opening} onChange={e=>setOpening(e.target.value)}/></label><p className="text-sm">The first opening count establishes the baseline and includes earlier activity. Later sessions carry forward the last approved physical count. Cash receipts after a count—including between sessions—are included in the next session. Record any bank deposit, float change or other physical movement here.</p>{active&&<p>This location has a drawer awaiting closeout or review.</p>}<button className={button} disabled={busy||!location||Boolean(active)||notes.trim().length<5} onClick={()=>{if(window.confirm('Confirm this opening cash balance and the notes below?'))action({action:'OPEN',locationId:location,openingAmount:Number(opening),notes,confirmed:true})}}>Confirm opening balance</button></section>
 <label className="block">Action or review notes (required)<textarea className={field} rows={3} minLength={5} maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label>
 <section className="space-y-3"><h2 className="text-xl font-semibold">Drawer sessions</h2>{data.sessions.length===0&&<p>No drawer sessions yet.</p>}{data.sessions.map(s=><button key={s.id} className="block w-full rounded border bg-white p-3 text-left" disabled={busy} onClick={()=>inspect(s.id).catch(e=>setError(e.message))}>{data.locations.find(l=>l.id===s.locationId)?.name||'Location'} · {s.status} · {new Date(s.createdAt).toLocaleString()} · opening {usd(s.openingCents)}{s.varianceCents!==null?' · variance '+usd(s.varianceCents):''}</button>)}</section>
 {preview&&<section className="space-y-4 rounded border bg-white p-5"><h2 className="text-xl font-semibold">Selected drawer · {preview.session.status}</h2><button className={button} disabled={busy} onClick={()=>inspect(preview.session.id).catch(e=>setError(e.message))}>Refresh selected drawer</button><p>{preview.session.notes}</p>{preview.snapshot&&<><p>Opening {usd(preview.snapshot.openingCents)} · expected {usd(preview.snapshot.expectedCents)}</p><details><summary>Verified receipts, refunds and cash movements</summary><div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Entry</th><th className="p-2 text-left">Reference / reason</th><th className="p-2 text-right">USD</th></tr></thead><tbody>{preview.snapshot.receipts.map(r=><tr key={r.key}><td className="p-2">{r.kind}</td><td className="p-2">{r.reference}</td><td className="p-2 text-right">{usd(r.amountCents)}</td></tr>)}{preview.snapshot.movements.map(m=><tr key={m.id}><td className="p-2">Cash movement</td><td className="p-2">{m.reason}</td><td className="p-2 text-right">{usd(m.amountCents)}</td></tr>)}</tbody></table></div></details></>}
 {preview.session.status==='OPEN'&&<><div className="grid gap-3 sm:grid-cols-2"><label>Physical cash movement<select aria-label="Physical cash movement" className={field} value={direction} onChange={e=>setDirection(e.target.value)}><option value="OUT">Cash removed</option><option value="IN">Cash added</option></select></label><label>Movement amount USD<input className={field} type="number" step="0.01" min="0.01" max="1000000" value={amount} onChange={e=>setAmount(e.target.value)}/></label></div><button className={button} disabled={busy||notes.trim().length<5||!amount} onClick={()=>{if(window.confirm('Confirm this physical cash movement actually occurred?'))action({action:'MOVEMENT',id:preview.session.id,version:preview.session.version,direction,amount:Number(amount),reason:notes,confirmed:true})}}>Record actual cash movement</button><label className="block">Physical cash count USD<input className={field} type="number" step="0.01" min="0" max="1000000" value={count} onChange={e=>setCount(e.target.value)}/></label><button className={button} disabled={busy||notes.trim().length<5||count===''||!preview.hash} onClick={()=>{if(window.confirm('Freeze this physical count and its current receipts for manager review? New receipts will belong to the next drawer session.'))action({action:'COUNT',id:preview.session.id,version:preview.session.version,countedAmount:Number(count),expectedHash:preview.hash,notes,confirmed:true})}}>Submit physical count</button></>}
 {preview.session.status!=='OPEN'&&<><p>Physical count {usd(preview.session.countCents)} · difference {usd(preview.session.varianceCents)}</p>{preview.session.reviewNotes&&<p>Manager review: {preview.session.reviewNotes}</p>}{preview.session.status==='COUNTED'&&data.canApprove&&<><p>A different manager must review any difference between expected and counted cash.</p><button className={button} disabled={busy||notes.trim().length<5} onClick={()=>{if(window.confirm('Approve and permanently close this reviewed drawer count?'))action({action:'APPROVE',id:preview.session.id,version:preview.session.version,notes,confirmed:true})}}>Approve closeout</button></>}{preview.session.status==='CLOSED'&&<a className="inline-block underline" href={'/api/operations/cash-drawer?id='+encodeURIComponent(preview.session.id)+'&format=csv'}>Download approved closeout CSV</a>}</>}
 </section>}
 </>}
 </main>
}
