'use client';
import { useState } from 'react';
import { useOperation } from '@/components/operations/use-operation';
import { Button } from '@/components/ui/button';
type Order = { id: string; poNumber: string; status: string; totalAmount: string; vendor: { name: string }; items: { id: string; productName: string; quantityOrdered: number; quantityReceived: number }[] };
export default function PurchasingPage() {
  const { data, error, busy, save, load } = useOperation<{ orders: Order[]; vendors: { id: string; name: string }[]; products: { id: string; name: string; cost: string | null; quantityOnHand: number; reorderLevel: number; reorderQuantity: number }[] }>('/api/operations/purchasing');
  const [vendorId, setVendorId] = useState(''); const [lines, setLines] = useState([{ productId: '', quantityOrdered: 1, unitCost: 0 }]); const [received, setReceived] = useState<Record<string, number>>({});
  const [vendorName, setVendorName] = useState(''); const [vendorError, setVendorError] = useState('');
  async function addVendor(e: React.FormEvent) { e.preventDefault(); setVendorError(''); try { const r = await fetch('/api/vendors', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: vendorName }) }); const v = await r.json(); if (!r.ok) throw new Error(v.error || 'Unable to create vendor'); setVendorName(''); await load(); setVendorId(v.id); } catch(e) { setVendorError(e instanceof Error ? e.message : 'Unable to create vendor'); } }
  return <main className="p-6 max-w-6xl space-y-6"><h1 className="text-2xl font-bold">Purchasing & receiving</h1>{(error || vendorError) && <p role="alert" className="text-red-700">{error || vendorError}<Button variant="outline" onClick={load}>Reload</Button></p>}
    <form onSubmit={addVendor} className="flex gap-2 flex-wrap"><label>New vendor<input required className="block border rounded p-2" maxLength={150} value={vendorName} onChange={e => setVendorName(e.target.value)}/></label><Button variant="outline">Add vendor</Button></form>
    {data && <form className="border rounded-xl p-5 space-y-4" onSubmit={async e => { e.preventDefault(); if (await save({ action: 'create', vendorId, items: lines })) setLines([{ productId: '', quantityOrdered: 1, unitCost: 0 }]); }}><h2 className="text-xl font-semibold">New purchase order</h2><label className="block">Vendor<select required className="block border rounded p-2" value={vendorId} onChange={e => setVendorId(e.target.value)}><option value="">Choose vendor</option>{data.vendors.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label>
      {lines.map((line, i) => <div className="flex gap-3 flex-wrap" key={i}><label>Product<select required className="block border rounded p-2" value={line.productId} onChange={e => { const p = data.products.find(p => p.id === e.target.value); setLines(lines.map((l, j) => j === i ? { ...l, productId: e.target.value, unitCost: Number(p?.cost || 0) } : l)); }}><option value="">Choose product</option>{data.products.map(p => <option key={p.id} value={p.id}>{p.name} (stock: {p.quantityOnHand})</option>)}</select></label><label>Quantity<input required type="number" className="block border rounded p-2 w-24" min={1} max={100000} value={line.quantityOrdered} onChange={e => setLines(lines.map((l, j) => j === i ? { ...l, quantityOrdered: Number(e.target.value) } : l))}/></label><label>Unit cost<input required type="number" step="0.01" min="0" className="block border rounded p-2 w-28" value={line.unitCost} onChange={e => setLines(lines.map((l, j) => j === i ? { ...l, unitCost: Number(e.target.value) } : l))}/></label>{lines.length > 1 && <Button variant="ghost" type="button" onClick={() => setLines(lines.filter((_, j) => i !== j))}>Remove</Button>}</div>)}
      <div className="flex gap-2"><Button type="button" variant="outline" disabled={lines.length >= 100} onClick={() => setLines([...lines, { productId: '', quantityOrdered: 1, unitCost: 0 }])}>Add line</Button><Button disabled={busy}>Save draft order</Button></div></form>}
    <section className="space-y-4"><h2 className="text-xl font-semibold">Orders</h2>{data?.orders.map(order => <article className="border rounded-xl p-5 space-y-3" key={order.id}><h3 className="font-semibold">{order.vendor.name} · ${Number(order.totalAmount).toFixed(2)} · {order.status}</h3><p className="text-xs text-slate-500">{order.poNumber}</p>{order.items.map(item => <div className="flex gap-3 items-center flex-wrap" key={item.id}><span>{item.productName}: {item.quantityReceived} / {item.quantityOrdered} received</span>{['submitted', 'partial'].includes(order.status) && <label>Receive now<input type="number" min={0} max={item.quantityOrdered - item.quantityReceived} className="border rounded p-2 w-24 ml-2" value={received[item.id] || 0} onChange={e => setReceived({ ...received, [item.id]: Number(e.target.value) })}/></label>}</div>)}<div className="flex gap-2">{order.status === 'draft' && <Button disabled={busy} onClick={() => save({ action: 'submitted', id: order.id })}>Mark submitted</Button>}{['submitted', 'partial'].includes(order.status) && <Button disabled={busy} onClick={async () => { if (await save({ action: 'receive', id: order.id, items: order.items.filter(i => (received[i.id] || 0) > 0).map(i => ({ itemId: i.id, quantityReceived: received[i.id] })) })) setReceived({}); }}>Receive items</Button>}{['draft', 'submitted', 'partial'].includes(order.status) && <Button variant="outline" disabled={busy} onClick={() => save({ action: 'cancelled', id: order.id })}>Cancel remaining order</Button>}</div></article>)}</section>
  </main>;
}
