'use client';
import { useState } from 'react';
import { useOperation } from '@/components/operations/use-operation';
import { Button } from '@/components/ui/button';
type Result = { id: string; feature: string; model: string; status: string; createdAt: string; output: { title?: string; summary?: string; draftText?: string; error?: string; suggestions?: { text: string; sourceIds: string[] }[]; limitations?: string[] }; input: { sources?: { id: string; type: string; title?: string; name?: string }[] }; tokens: number | null; costUsd: string | null; reviewNotes: string | null };
export default function AIWorkspacePage() {
  const ai = useOperation<{ rows: Result[]; features: { id: string; name: string }[]; clients: { id: string; firstName: string; lastName: string }[]; configured: boolean; canReview: boolean; usage: { _count: number; _sum: { tokens: number | null; costUsd: string | null } } }>('/api/operations/ai');
  const kb = useOperation<{ documents: { id: string; title: string; content: string; sourceUrl: string | null }[]; canEdit: boolean }>('/api/operations/knowledge');
  const [feature, setFeature] = useState('front-desk'); const [instruction, setInstruction] = useState(''); const [clientId, setClientId] = useState('');
  const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [sourceUrl, setSourceUrl] = useState(''); const [notes, setNotes] = useState<Record<string, string>>({});
  return <main className="p-6 space-y-7 max-w-6xl"><h1 className="text-2xl font-bold">AI review & knowledge</h1><p>Generate drafts from your business records, inspect their sources, and review them before use. Approval records a review; it does not send a message or change a booking.</p>
    {(ai.error || kb.error) && <div className="text-red-700" role="alert">{ai.error || kb.error} <Button variant="outline" onClick={() => { void ai.load(); void kb.load(); }}>Reload</Button></div>}
    {!ai.data && !ai.error && <p role="status">Loading AI workspace…</p>}
    {ai.data && <>
      <div className="rounded-lg border p-4">Last 30 days: {ai.data.usage._count} requests · {ai.data.usage._sum.tokens ?? 'Unreported'} tokens · {ai.data.usage._sum.costUsd === null ? 'Cost not reported' : `$${Number(ai.data.usage._sum.costUsd).toFixed(4)} reported provider cost`}. Requests without provider usage are excluded from totals.</div>
      {!ai.data.configured && <p>AI needs an enabled provider configuration before drafts can be generated.</p>}
      <form className="rounded-xl border bg-white p-5 space-y-4" onSubmit={e => { e.preventDefault(); void ai.save({ feature, instruction, ...(clientId ? { clientId } : {}) }); }}>
        <label className="block">Task<select className="block border p-2 rounded w-full" value={feature} onChange={e => setFeature(e.target.value)}>{ai.data.features.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</select></label>
        {['client-summary', 'rebooking'].includes(feature) && <label className="block">Client<select required className="block border rounded p-2 w-full" value={clientId} onChange={e => setClientId(e.target.value)}><option value="">Choose client</option>{ai.data.clients.map(c => <option key={c.id} value={c.id}>{c.firstName} {c.lastName}</option>)}</select></label>}
        <label className="block">Request<textarea required maxLength={4000} className="block border rounded p-3 w-full min-h-24" value={instruction} onChange={e => setInstruction(e.target.value)} placeholder="For example: explain which products need restocking and cite the current stock records."/></label>
        <Button disabled={ai.busy || !ai.data.configured}>Generate draft</Button>
      </form>
      <section className="space-y-4"><h2 className="text-xl font-semibold">Drafts and review history</h2>{!ai.data.rows.length && <p>No AI requests yet.</p>}{ai.data.rows.map(row => <article className="border rounded-xl p-5 space-y-3 bg-white" key={row.id}><div className="flex justify-between gap-3"><h3 className="font-semibold">{row.output.title || row.feature}</h3><span>{row.status}</span></div><p className="text-sm text-slate-600">{new Date(row.createdAt).toLocaleString()} · {row.model} · {row.tokens ?? 'Unreported'} tokens · {row.costUsd === null ? 'Cost unreported' : `$${row.costUsd}`}</p>
        {row.output.error && <p role="alert" className="text-red-700">{row.output.error}</p>}{row.output.summary && <p>{row.output.summary}</p>}{row.output.draftText && <pre className="whitespace-pre-wrap bg-slate-50 p-3 rounded font-sans">{row.output.draftText}</pre>}
        {row.output.suggestions?.map((s, i) => <div key={i}><p>{s.text}</p><p className="text-xs text-slate-500">Sources: {s.sourceIds.length ? s.sourceIds.map(id => row.input.sources?.find(src => src.id === id)?.title || row.input.sources?.find(src => src.id === id)?.name || id).join(', ') : 'User request only'}</p></div>)}
        {!!row.output.limitations?.length && <p className="text-sm text-slate-600">Limitations: {row.output.limitations.join(' ')}</p>}
        {row.input.sources?.length ? <details><summary className="cursor-pointer underline">Inspect source records</summary><pre className="whitespace-pre-wrap text-xs overflow-auto max-h-80">{JSON.stringify(row.input.sources, null, 2)}</pre></details> : null}
        {row.status === 'DRAFT' && ai.data?.canReview && <div className="space-y-2"><label className="block">Review notes<textarea className="block border p-2 rounded w-full" value={notes[row.id] || ''} maxLength={2000} onChange={e => setNotes({ ...notes, [row.id]: e.target.value })}/></label><div className="flex gap-2"><Button disabled={ai.busy} onClick={() => ai.save({ action: 'review', id: row.id, status: 'APPROVED', notes: notes[row.id] || '' })}>Approve draft</Button><Button variant="outline" disabled={ai.busy} onClick={() => ai.save({ action: 'review', id: row.id, status: 'REJECTED', notes: notes[row.id] || '' })}>Reject</Button></div></div>}{row.reviewNotes && <p>Review: {row.reviewNotes}</p>}
      </article>)}</section>
    </>}
    <section className="space-y-4"><h2 className="text-xl font-semibold">Business knowledge</h2><p>Add policies, service descriptions and instructions to use as sources in knowledge search.</p>{kb.data?.canEdit && <form className="space-y-3" onSubmit={async e => { e.preventDefault(); if (await kb.save({ action: 'save', title, content, ...(sourceUrl ? { sourceUrl } : {}) })) { setTitle(''); setContent(''); setSourceUrl(''); } }}><label className="block">Title<input required className="block border rounded p-2 w-full" maxLength={200} value={title} onChange={e => setTitle(e.target.value)}/></label><label className="block">Content<textarea required className="block border rounded p-2 w-full min-h-32" maxLength={30000} value={content} onChange={e => setContent(e.target.value)}/></label><label className="block">Source URL (optional HTTPS)<input type="url" className="block border rounded p-2 w-full" value={sourceUrl} onChange={e => setSourceUrl(e.target.value)}/></label><Button disabled={kb.busy}>Save document</Button></form>}
      {kb.data?.documents.map(d => <article key={d.id} className="border rounded p-4"><h3 className="font-semibold">{d.title}</h3><details><summary>Read document</summary><p className="whitespace-pre-wrap">{d.content}</p></details>{d.sourceUrl && <a className="underline" href={d.sourceUrl} target="_blank" rel="noreferrer">Original source</a>}{kb.data?.canEdit && <Button variant="ghost" disabled={kb.busy} onClick={() => kb.save({ action: 'archive', id: d.id })}>Archive</Button>}</article>)}
    </section>
  </main>;
}
