/**
 * Scenario data for AI feature pages — generated by
 * scripts/build-fixture-data.cjs. Do not edit by hand.
 *
 * Every scenario fills EVERY field of its feature, so one click populates the
 * whole form. Values are fictional and match the page's own input options.
 */
import type { AIFixture } from "./AIFixtures";

export const AI_FIXTURES: Record<string, AIFixture> = {
  "translate": {
    "key": "translate",
    "label": "Translation",
    "description": "Translate a client-facing message into another language.",
    "fields": [
      "text",
      "targetLanguage",
      "context"
    ],
    "scenarios": [
      {
        "label": "Appointment reminder",
        "hint": "Short SMS confirmation",
        "values": {
          "text": "Your appointment is confirmed for Tuesday at 10:00. Please arrive five minutes early.",
          "targetLanguage": "Spanish",
          "context": "Salon appointment confirmation sent by SMS."
        }
      },
      {
        "label": "Running late",
        "hint": "Apology message to a client",
        "values": {
          "text": "We are running about fifteen minutes behind schedule. Thank you for your patience.",
          "targetLanguage": "French",
          "context": "Sent to a waiting client."
        }
      },
      {
        "label": "Aftercare advice",
        "hint": "Post-treatment instructions",
        "values": {
          "text": "Please avoid washing your hair for 48 hours and use a sulphate-free shampoo.",
          "targetLanguage": "Portuguese",
          "context": "Colour aftercare instructions."
        }
      }
    ]
  },
  "message-generator": {
    "key": "message-generator",
    "label": "Message Generator",
    "description": "Draft a message to a client for a chosen purpose and tone.",
    "fields": [
      "recipientName",
      "purpose",
      "tone",
      "details"
    ],
    "scenarios": [
      {
        "label": "Appointment reminder",
        "hint": "Friendly reminder",
        "values": {
          "recipientName": "Avery",
          "purpose": "appointment reminder",
          "tone": "friendly",
          "details": "Tuesday 10:00 with Jordan for a colour appointment."
        }
      },
      {
        "label": "Re-engagement",
        "hint": "Win back a lapsed client",
        "values": {
          "recipientName": "Morgan",
          "purpose": "re-engagement offer",
          "tone": "warm",
          "details": "Has not visited in four months; previously a monthly regular."
        }
      },
      {
        "label": "Birthday wish",
        "hint": "Short celebratory note",
        "values": {
          "recipientName": "Riley",
          "purpose": "birthday greeting",
          "tone": "cheerful",
          "details": "Offer a complimentary treatment on their next visit."
        }
      }
    ]
  },
  "review-response": {
    "key": "review-response",
    "label": "Review Response",
    "description": "Draft a reply to a customer review.",
    "fields": [
      "review",
      "rating",
      "customerName",
      "tone"
    ],
    "scenarios": [
      {
        "label": "Mixed 3-star",
        "hint": "Acknowledge the wait",
        "values": {
          "review": "Lovely stylist and a calm salon, but I waited about twenty minutes past my appointment time.",
          "rating": "3",
          "customerName": "Jordan",
          "tone": "apologetic and appreciative"
        }
      },
      {
        "label": "Glowing 5-star",
        "hint": "Thank a happy client",
        "values": {
          "review": "Absolutely thrilled with my balayage. The colour is exactly what I asked for and it lasted months.",
          "rating": "5",
          "customerName": "Casey",
          "tone": "warm and grateful"
        }
      },
      {
        "label": "Poor 1-star",
        "hint": "Service recovery",
        "values": {
          "review": "The colour came out patchy and I was told to come back another day to fix it.",
          "rating": "1",
          "customerName": "Taylor",
          "tone": "sincere and corrective"
        }
      }
    ]
  },
  "business-insights": {
    "key": "business-insights",
    "label": "Business Insights",
    "description": "Summarise operating performance over a period.",
    "fields": [
      "periodDays",
      "locationId"
    ],
    "scenarios": [
      {
        "label": "Last 30 days",
        "hint": "Monthly performance",
        "values": {
          "periodDays": "30",
          "locationId": ""
        }
      },
      {
        "label": "Last 90 days",
        "hint": "Quarterly trend",
        "values": {
          "periodDays": "90",
          "locationId": ""
        }
      },
      {
        "label": "Last 7 days",
        "hint": "This week",
        "values": {
          "periodDays": "7",
          "locationId": ""
        }
      }
    ]
  },
  "appointment-optimizer": {
    "key": "appointment-optimizer",
    "label": "Appointment Optimizer",
    "description": "Find schedule gaps and suggest improvements for a day.",
    "fields": [
      "date",
      "staffId",
      "optimize"
    ],
    "scenarios": [
      {
        "label": "Fill the gaps",
        "hint": "Maximise utilisation",
        "values": {
          "date": "2026-10-06",
          "staffId": "",
          "optimize": "gaps"
        }
      },
      {
        "label": "Reduce idle time",
        "hint": "Balance the roster",
        "values": {
          "date": "2026-10-07",
          "staffId": "",
          "optimize": "idle"
        }
      },
      {
        "label": "Busy Saturday",
        "hint": "Peak-day review",
        "values": {
          "date": "2026-10-10",
          "staffId": "",
          "optimize": "gaps"
        }
      }
    ]
  },
  "staff-matcher": {
    "key": "staff-matcher",
    "label": "Staff Matcher",
    "description": "Match a client and service to the best-suited staff member.",
    "fields": [
      "clientId",
      "serviceId",
      "preferences"
    ],
    "scenarios": [
      {
        "label": "Curly hair specialist",
        "hint": "Experienced stylist",
        "values": {
          "clientId": "",
          "serviceId": "",
          "preferences": "Prefers a stylist experienced with curly hair."
        }
      },
      {
        "label": "Colour expert",
        "hint": "Balayage experience",
        "values": {
          "clientId": "",
          "serviceId": "",
          "preferences": "Wants someone with colour-correction experience."
        }
      },
      {
        "label": "No preference",
        "hint": "Next available",
        "values": {
          "clientId": "",
          "serviceId": "",
          "preferences": "No preference; happy with the next available stylist."
        }
      }
    ]
  },
  "staff-shift-preferences": {
    "key": "staff-shift-preferences",
    "label": "Shift Preferences",
    "description": "Infer preferred shifts from a staff member's history.",
    "fields": [
      "staffId",
      "lookbackDays"
    ],
    "scenarios": [
      {
        "label": "Last 60 days",
        "hint": "Standard look-back",
        "values": {
          "staffId": "",
          "lookbackDays": "60"
        }
      },
      {
        "label": "Last 30 days",
        "hint": "Recent pattern",
        "values": {
          "staffId": "",
          "lookbackDays": "30"
        }
      },
      {
        "label": "Last 180 days",
        "hint": "Long-run pattern",
        "values": {
          "staffId": "",
          "lookbackDays": "180"
        }
      }
    ]
  },
  "checkin-recommend": {
    "key": "checkin-recommend",
    "label": "Check-in Recommendations",
    "description": "Suggest add-ons and next steps when a client checks in.",
    "fields": [
      "clientId",
      "appointmentId",
      "reason"
    ],
    "scenarios": [
      {
        "label": "Colour client",
        "hint": "Add-on suggestions",
        "values": {
          "clientId": "",
          "appointmentId": "",
          "reason": "Client is here for a colour appointment and previously added a treatment."
        }
      },
      {
        "label": "New client",
        "hint": "First visit",
        "values": {
          "clientId": "",
          "appointmentId": "",
          "reason": "First visit; no history on file yet."
        }
      },
      {
        "label": "Regular client",
        "hint": "Frequent visitor",
        "values": {
          "clientId": "",
          "appointmentId": "",
          "reason": "Visits every six weeks and usually books a blowout afterwards."
        }
      }
    ]
  },
  "waitlist-intelligence": {
    "key": "waitlist-intelligence",
    "label": "Waitlist Intelligence",
    "description": "Rank waitlisted clients for a given opening.",
    "fields": [
      "appointmentId",
      "waitlistClientIds",
      "reason"
    ],
    "scenarios": [
      {
        "label": "Saturday opening",
        "hint": "Rank waitlisted clients",
        "values": {
          "appointmentId": "",
          "waitlistClientIds": "",
          "reason": "Saturday morning slot released; several clients are waiting."
        }
      },
      {
        "label": "Cancellation slot",
        "hint": "Fill a late gap",
        "values": {
          "appointmentId": "",
          "waitlistClientIds": "",
          "reason": "Late cancellation with two hours notice."
        }
      }
    ]
  },
  "inventory-autopilot": {
    "key": "inventory-autopilot",
    "label": "Inventory Autopilot",
    "description": "Review stock and suggest reorders.",
    "fields": [
      "lookbackDays",
      "locationId"
    ],
    "scenarios": [
      {
        "label": "Last 90 days",
        "hint": "Standard review",
        "values": {
          "lookbackDays": "90",
          "locationId": ""
        }
      },
      {
        "label": "Last 30 days",
        "hint": "Recent movement",
        "values": {
          "lookbackDays": "30",
          "locationId": ""
        }
      },
      {
        "label": "Last 180 days",
        "hint": "Seasonal trend",
        "values": {
          "lookbackDays": "180",
          "locationId": ""
        }
      }
    ]
  },
  "before-after": {
    "key": "before-after",
    "label": "Before & After",
    "description": "Compare two service photographs.",
    "fields": [
      "clientId",
      "beforeId",
      "afterId",
      "serviceName"
    ],
    "scenarios": [
      {
        "label": "Colour transformation",
        "hint": "Before/after photos",
        "values": {
          "clientId": "",
          "beforeId": "",
          "afterId": "",
          "serviceName": "Balayage"
        }
      },
      {
        "label": "Cut and style",
        "hint": "Restyle comparison",
        "values": {
          "clientId": "",
          "beforeId": "",
          "afterId": "",
          "serviceName": "Women's Haircut"
        }
      }
    ]
  },
  "booking-assistant": {
    "key": "booking-assistant",
    "label": "Booking Assistant",
    "description": "Suggest appointment slots from a natural-language request.",
    "fields": [
      "message",
      "clientId"
    ],
    "scenarios": [
      {
        "label": "Afternoon request",
        "hint": "Preferred stylist",
        "values": {
          "message": "I would like a colour appointment next Tuesday afternoon, ideally with Jordan.",
          "clientId": ""
        }
      },
      {
        "label": "Weekend slot",
        "hint": "Saturday morning",
        "values": {
          "message": "Do you have anything free on Saturday morning for a cut and blow dry?",
          "clientId": ""
        }
      },
      {
        "label": "Reschedule",
        "hint": "Move an appointment",
        "values": {
          "message": "I need to move my appointment from Friday to the following week if possible.",
          "clientId": ""
        }
      }
    ]
  },
  "therapist-match": {
    "key": "therapist-match",
    "label": "Therapist Match",
    "description": "Match a client to a suitable therapist for a service.",
    "fields": [
      "clientId",
      "serviceId",
      "preferredAt"
    ],
    "scenarios": [
      {
        "label": "Next Tuesday",
        "hint": "Preferred date",
        "values": {
          "clientId": "",
          "serviceId": "",
          "preferredAt": "2026-10-06T14:00"
        }
      },
      {
        "label": "Saturday morning",
        "hint": "Weekend slot",
        "values": {
          "clientId": "",
          "serviceId": "",
          "preferredAt": "2026-10-10T10:00"
        }
      }
    ]
  },
  "voice-receptionist": {
    "key": "voice-receptionist",
    "label": "Voice Receptionist",
    "description": "Simulate an incoming caller and draft the receptionist reply.",
    "fields": [
      "speechInput",
      "from",
      "context",
      "language"
    ],
    "scenarios": [
      {
        "label": "New booking",
        "hint": "First-time caller",
        "values": {
          "speechInput": "Hi, I would like to book a haircut for Saturday morning if you have anything free.",
          "from": "+18045550100",
          "context": "First-time caller.",
          "language": "en"
        }
      },
      {
        "label": "Opening hours",
        "hint": "General enquiry",
        "values": {
          "speechInput": "What time do you close on a Friday?",
          "from": "+18045550101",
          "context": "Enquiry about opening hours.",
          "language": "en"
        }
      },
      {
        "label": "Cancellation",
        "hint": "Cancel a booking",
        "values": {
          "speechInput": "I need to cancel my appointment tomorrow, I am unwell.",
          "from": "+18045550102",
          "context": "Existing client cancelling.",
          "language": "en"
        }
      }
    ]
  },
  "skin-kiosk": {
    "key": "skin-kiosk",
    "label": "Skin Kiosk",
    "description": "Cosmetic observations from a photo, within consent limits.",
    "fields": [
      "clientId",
      "concerns",
      "imageData",
      "kioskId"
    ],
    "scenarios": [
      {
        "label": "Routine enquiry",
        "hint": "General skincare",
        "values": {
          "clientId": "",
          "concerns": "Interested in a general cosmetic skincare routine.",
          "imageData": "",
          "kioskId": "demo-kiosk-1"
        }
      },
      {
        "label": "Dryness concern",
        "hint": "Cosmetic hydration",
        "values": {
          "clientId": "",
          "concerns": "Skin feels tight in the afternoon.",
          "imageData": "",
          "kioskId": "demo-kiosk-1"
        }
      }
    ]
  },
  "style": {
    "key": "style",
    "label": "Style Recommendations",
    "description": "Suggest hairstyles from a photo and stated preferences.",
    "fields": [
      "hairLength",
      "hairType",
      "lifestyle",
      "maintenance",
      "notes"
    ],
    "scenarios": [
      {
        "label": "Office professional",
        "hint": "Low maintenance",
        "values": {
          "hairLength": "medium",
          "hairType": "wavy",
          "lifestyle": "low maintenance, works in an office",
          "maintenance": "moderate",
          "notes": "Prefers a style that can be tied back for work."
        }
      },
      {
        "label": "Curly definition",
        "hint": "Embrace natural curl",
        "values": {
          "hairLength": "long",
          "hairType": "curly",
          "lifestyle": "active outdoors",
          "maintenance": "high",
          "notes": "Wants more definition and less frizz."
        }
      },
      {
        "label": "Short restyle",
        "hint": "Big change",
        "values": {
          "hairLength": "short",
          "hairType": "straight",
          "lifestyle": "busy parent",
          "maintenance": "low",
          "notes": "Ready for a significant change from long hair."
        }
      }
    ]
  },
  "revenue": {
    "key": "revenue",
    "label": "Revenue Forecast",
    "description": "Forecast revenue and surface opportunities for a period.",
    "fields": [
      "timeframe",
      "includeSeasonality"
    ],
    "scenarios": [
      {
        "label": "Next month",
        "hint": "Include seasonality",
        "values": {
          "timeframe": "next_month",
          "includeSeasonality": "true"
        }
      },
      {
        "label": "Next quarter",
        "hint": "Planning view",
        "values": {
          "timeframe": "next_quarter",
          "includeSeasonality": "true"
        }
      },
      {
        "label": "Next year",
        "hint": "Annual outlook",
        "values": {
          "timeframe": "next_year",
          "includeSeasonality": "false"
        }
      }
    ]
  },
  "scheduling": {
    "key": "scheduling",
    "label": "Smart Scheduling",
    "description": "Suggest an appointment slot from a client request.",
    "fields": [
      "preferredStaff",
      "preferredTime",
      "constraints"
    ],
    "scenarios": [
      {
        "label": "Afternoon slot",
        "hint": "Travel constraint",
        "values": {
          "preferredStaff": "",
          "preferredTime": "afternoon",
          "constraints": "Avoid appointments before 10:00; client is travelling from out of town."
        }
      },
      {
        "label": "Morning slot",
        "hint": "Early preference",
        "values": {
          "preferredStaff": "",
          "preferredTime": "morning",
          "constraints": "Client prefers to be finished before lunch."
        }
      },
      {
        "label": "Flexible",
        "hint": "Any time",
        "values": {
          "preferredStaff": "",
          "preferredTime": "flexible",
          "constraints": "No constraints; happy with any available slot."
        }
      }
    ]
  },
  "inventory": {
    "key": "inventory",
    "label": "Inventory Forecast",
    "description": "Forecast demand and flag items to reorder.",
    "fields": [
      "category",
      "timeframe",
      "seasonalFactor"
    ],
    "scenarios": [
      {
        "label": "Hair care, 30d",
        "hint": "Standard review",
        "values": {
          "category": "Hair Care",
          "timeframe": "30",
          "seasonalFactor": "normal"
        }
      },
      {
        "label": "Colour products",
        "hint": "Peak season",
        "values": {
          "category": "Color Products",
          "timeframe": "30",
          "seasonalFactor": "holiday"
        }
      },
      {
        "label": "Skincare",
        "hint": "Summer trend",
        "values": {
          "category": "Skincare",
          "timeframe": "30",
          "seasonalFactor": "summer"
        }
      }
    ]
  },
  "pricing": {
    "key": "pricing",
    "label": "Price Optimizer",
    "description": "Suggest a price for a service based on position and goal.",
    "fields": [
      "service",
      "currentPrice",
      "marketPosition",
      "goal"
    ],
    "scenarios": [
      {
        "label": "Balayage",
        "hint": "Increase revenue",
        "values": {
          "service": "Balayage",
          "currentPrice": "180",
          "marketPosition": "mid",
          "goal": "increase_revenue"
        }
      },
      {
        "label": "Blowout",
        "hint": "Stay competitive",
        "values": {
          "service": "Blowout",
          "currentPrice": "45",
          "marketPosition": "budget",
          "goal": "stay_competitive"
        }
      },
      {
        "label": "Massage",
        "hint": "Premium positioning",
        "values": {
          "service": "Massage",
          "currentPrice": "95",
          "marketPosition": "premium",
          "goal": "premium_positioning"
        }
      }
    ]
  },
  "reactivation": {
    "key": "reactivation",
    "label": "Reactivation Campaigns",
    "description": "Draft a win-back campaign for clients who have not returned.",
    "fields": [
      "inactiveDays",
      "segment",
      "campaignType"
    ],
    "scenarios": [
      {
        "label": "Lapsed clients",
        "hint": "Win-back offer",
        "values": {
          "inactiveDays": "90",
          "segment": "lapsed",
          "campaignType": "we_miss_you"
        }
      },
      {
        "label": "VIP clients",
        "hint": "Retention focus",
        "values": {
          "inactiveDays": "60",
          "segment": "vip",
          "campaignType": "loyalty_reminder"
        }
      },
      {
        "label": "New clients",
        "hint": "Second-visit nudge",
        "values": {
          "inactiveDays": "45",
          "segment": "new",
          "campaignType": "product_repurchase"
        }
      }
    ]
  },
  "social-media": {
    "key": "social-media",
    "label": "Social Media",
    "description": "Draft a social post for a platform.",
    "fields": [
      "platform",
      "postType",
      "topic",
      "tone"
    ],
    "scenarios": [
      {
        "label": "Transformation post",
        "hint": "Before/after",
        "values": {
          "platform": "instagram",
          "postType": "transformation",
          "topic": "behind the scenes of a colour transformation",
          "tone": "professional"
        }
      },
      {
        "label": "Weekend offer",
        "hint": "Promotional",
        "values": {
          "platform": "instagram",
          "postType": "promotion",
          "topic": "20% off colour services this weekend",
          "tone": "exciting"
        }
      },
      {
        "label": "Hair tips",
        "hint": "Educational",
        "values": {
          "platform": "facebook",
          "postType": "tips",
          "topic": "how to protect hair from heat styling",
          "tone": "casual"
        }
      }
    ]
  },
  "upsell": {
    "key": "upsell",
    "label": "Upsell Suggestions",
    "description": "Suggest add-ons for a client mid-visit.",
    "fields": [
      "clientName",
      "currentService",
      "clientHistory"
    ],
    "scenarios": [
      {
        "label": "Haircut client",
        "hint": "Styling add-on",
        "values": {
          "clientName": "Avery",
          "currentService": "Haircut",
          "clientHistory": "Regular every 8 weeks; has previously added a gloss treatment."
        }
      },
      {
        "label": "Colour client",
        "hint": "Aftercare products",
        "values": {
          "clientName": "Morgan",
          "currentService": "Hair Color",
          "clientHistory": "Colours every 10 weeks; buys retail shampoo occasionally."
        }
      },
      {
        "label": "First facial",
        "hint": "Skincare follow-up",
        "values": {
          "clientName": "Riley",
          "currentService": "Facial",
          "clientHistory": "First visit; interested in a simple home routine."
        }
      }
    ]
  },
  "waitlist": {
    "key": "waitlist",
    "label": "Waitlist Analysis",
    "description": "Review waitlist pressure for a day type.",
    "fields": [
      "currentWaitlist",
      "averageServiceTime",
      "staffAvailable",
      "dayType"
    ],
    "scenarios": [
      {
        "label": "Busy Saturday",
        "hint": "Peak pressure",
        "values": {
          "currentWaitlist": "6 clients waiting",
          "averageServiceTime": "45",
          "staffAvailable": "3",
          "dayType": "saturday"
        }
      },
      {
        "label": "Quiet weekday",
        "hint": "Low pressure",
        "values": {
          "currentWaitlist": "2 clients waiting",
          "averageServiceTime": "30",
          "staffAvailable": "4",
          "dayType": "weekday"
        }
      },
      {
        "label": "Holiday period",
        "hint": "Seasonal peak",
        "values": {
          "currentWaitlist": "9 clients waiting",
          "averageServiceTime": "60",
          "staffAvailable": "2",
          "dayType": "holiday"
        }
      }
    ]
  },
  "no-show": {
    "key": "no-show",
    "label": "No-show Predictor",
    "description": "Assess the risk of a client not attending.",
    "fields": [
      "clientName",
      "appointmentTime",
      "previousNoShows",
      "confirmationStatus"
    ],
    "scenarios": [
      {
        "label": "Unconfirmed booking",
        "hint": "Higher risk",
        "values": {
          "clientName": "Jordan",
          "appointmentTime": "Tuesday 10:00",
          "previousNoShows": "1",
          "confirmationStatus": "not confirmed"
        }
      },
      {
        "label": "Confirmed regular",
        "hint": "Lower risk",
        "values": {
          "clientName": "Casey",
          "appointmentTime": "Thursday 14:00",
          "previousNoShows": "0",
          "confirmationStatus": "confirmed"
        }
      },
      {
        "label": "Repeat no-show",
        "hint": "Highest risk",
        "values": {
          "clientName": "Taylor",
          "appointmentTime": "Saturday 09:00",
          "previousNoShows": "3",
          "confirmationStatus": "not confirmed"
        }
      }
    ]
  },
  "sentiment": {
    "key": "sentiment",
    "label": "Review Sentiment",
    "description": "Analyse a customer review for sentiment and themes.",
    "fields": [
      "review",
      "source"
    ],
    "scenarios": [
      {
        "label": "Mixed review",
        "hint": "Positive with a caveat",
        "values": {
          "review": "Lovely stylist and a calm salon, but I waited about twenty minutes past my appointment time.",
          "source": "Google"
        }
      },
      {
        "label": "Glowing review",
        "hint": "Fully positive",
        "values": {
          "review": "Absolutely thrilled with my balayage. The colour lasted months and the salon was spotless.",
          "source": "Google"
        }
      },
      {
        "label": "Angry review",
        "hint": "Fully negative",
        "values": {
          "review": "Terrible experience. The colour was patchy and the manager was dismissive when I complained.",
          "source": "Yelp"
        }
      }
    ]
  },
  "sleep-coach": {
    "key": "sleep-coach",
    "label": "Sleep Coach",
    "description": "Review sleep habits and suggest improvements.",
    "fields": [
      "bedtime",
      "wakeTime",
      "sleepQuality",
      "caffeineIntake",
      "screenTime",
      "exercise",
      "stress",
      "roomTemp",
      "noiseLevel"
    ],
    "scenarios": [
      {
        "label": "Restless weeknight",
        "hint": "Late screen use",
        "values": {
          "bedtime": "23:30",
          "wakeTime": "06:30",
          "sleepQuality": "5",
          "caffeineIntake": "true",
          "screenTime": "90",
          "exercise": "false",
          "stress": "7",
          "roomTemp": "warm",
          "noiseLevel": "noisy"
        }
      },
      {
        "label": "Good routine",
        "hint": "Consistent schedule",
        "values": {
          "bedtime": "22:00",
          "wakeTime": "06:30",
          "sleepQuality": "8",
          "caffeineIntake": "false",
          "screenTime": "20",
          "exercise": "true",
          "stress": "3",
          "roomTemp": "cool",
          "noiseLevel": "quiet"
        }
      },
      {
        "label": "Shift worker",
        "hint": "Irregular hours",
        "values": {
          "bedtime": "01:00",
          "wakeTime": "09:00",
          "sleepQuality": "4",
          "caffeineIntake": "true",
          "screenTime": "60",
          "exercise": "false",
          "stress": "6",
          "roomTemp": "cool",
          "noiseLevel": "quiet"
        }
      }
    ]
  },
  "symptom-checker": {
    "key": "symptom-checker",
    "label": "Symptom Checker",
    "description": "General wellbeing information for reported symptoms.",
    "fields": [
      "symptoms",
      "duration",
      "severity",
      "additionalInfo"
    ],
    "scenarios": [
      {
        "label": "Mild headache",
        "hint": "Short duration",
        "values": {
          "symptoms": "headache",
          "duration": "1 day",
          "severity": "mild",
          "additionalInfo": "Started yesterday evening; no other symptoms."
        }
      },
      {
        "label": "Cold symptoms",
        "hint": "A few days",
        "values": {
          "symptoms": "runny nose, sore throat, mild cough",
          "duration": "3 days",
          "severity": "moderate",
          "additionalInfo": "No fever; eating and drinking normally."
        }
      },
      {
        "label": "Persistent fatigue",
        "hint": "Longer duration",
        "values": {
          "symptoms": "fatigue, poor sleep",
          "duration": "2 weeks",
          "severity": "moderate",
          "additionalInfo": "Feeling tired most afternoons."
        }
      }
    ]
  },
  "posture-corrector": {
    "key": "posture-corrector",
    "label": "Posture Corrector",
    "description": "Suggest stretches and ergonomic changes.",
    "fields": [
      "occupation",
      "hoursSeated",
      "selectedPainAreas",
      "selectedIssues",
      "activityLevel"
    ],
    "scenarios": [
      {
        "label": "Desk worker",
        "hint": "Neck and shoulders",
        "values": {
          "occupation": "office administrator",
          "hoursSeated": "7",
          "selectedPainAreas": "neck",
          "selectedIssues": "forward head posture",
          "activityLevel": "light"
        }
      },
      {
        "label": "Standing role",
        "hint": "Lower back",
        "values": {
          "occupation": "retail assistant",
          "hoursSeated": "2",
          "selectedPainAreas": "lower back",
          "selectedIssues": "uneven weight bearing",
          "activityLevel": "moderate"
        }
      },
      {
        "label": "Active desk user",
        "hint": "Wrists and back",
        "values": {
          "occupation": "software developer",
          "hoursSeated": "8",
          "selectedPainAreas": "wrists, upper back",
          "selectedIssues": "rounded shoulders",
          "activityLevel": "active"
        }
      }
    ]
  },
  "skin-analyzer": {
    "key": "skin-analyzer",
    "label": "Skin Analyzer",
    "description": "Cosmetic skincare recommendations from a skin profile.",
    "fields": [
      "skinType",
      "concerns",
      "age",
      "lifestyle"
    ],
    "scenarios": [
      {
        "label": "Combination skin",
        "hint": "Dryness and dullness",
        "values": {
          "skinType": "combination",
          "concerns": "dryness, dullness",
          "age": "35",
          "lifestyle": "office work, limited sleep"
        }
      },
      {
        "label": "Oily skin",
        "hint": "Breakouts",
        "values": {
          "skinType": "oily",
          "concerns": "breakouts, enlarged pores",
          "age": "24",
          "lifestyle": "gym most days"
        }
      },
      {
        "label": "Sensitive skin",
        "hint": "Redness",
        "values": {
          "skinType": "sensitive",
          "concerns": "redness, reactivity",
          "age": "42",
          "lifestyle": "spends time outdoors"
        }
      }
    ]
  },
  "product-recommender": {
    "key": "product-recommender",
    "label": "Product Recommender",
    "description": "Suggest products for stated concerns.",
    "fields": [
      "skinType",
      "hairType",
      "selectedConcerns",
      "selectedAllergies",
      "budget"
    ],
    "scenarios": [
      {
        "label": "Mid-range routine",
        "hint": "Dryness",
        "values": {
          "skinType": "combination",
          "hairType": "wavy",
          "selectedConcerns": "dryness",
          "selectedAllergies": "fragrance",
          "budget": "mid-range"
        }
      },
      {
        "label": "Budget option",
        "hint": "Oily skin",
        "values": {
          "skinType": "oily",
          "hairType": "straight",
          "selectedConcerns": "breakouts",
          "selectedAllergies": "none",
          "budget": "budget"
        }
      },
      {
        "label": "Premium option",
        "hint": "Anti-ageing",
        "values": {
          "skinType": "dry",
          "hairType": "curly",
          "selectedConcerns": "fine lines",
          "selectedAllergies": "nuts",
          "budget": "premium"
        }
      }
    ]
  },
  "mental-health": {
    "key": "mental-health",
    "label": "Mental Health Check-in",
    "description": "A supportive check-in on mood and stress.",
    "fields": [
      "moodScore",
      "stressLevel",
      "message"
    ],
    "scenarios": [
      {
        "label": "Steady week",
        "hint": "Good mood",
        "values": {
          "moodScore": "8",
          "stressLevel": "3",
          "message": "I have been feeling pretty good this week and want to keep the momentum going."
        }
      },
      {
        "label": "Stressful week",
        "hint": "Higher stress",
        "values": {
          "moodScore": "4",
          "stressLevel": "8",
          "message": "Work has been overwhelming and I cannot switch off. My shoulders are tense and I am not sleeping well."
        }
      },
      {
        "label": "Mixed week",
        "hint": "Up and down",
        "values": {
          "moodScore": "6",
          "stressLevel": "5",
          "message": "Some days are fine and others are hard. I would like help finding a steadier routine."
        }
      }
    ]
  },
  "voice-settings": {
    "key": "voice-settings",
    "label": "Voice Receptionist Settings",
    "description": "Configure how the receptionist handles incoming calls.",
    "fields": [
      "businessName",
      "receptionistName",
      "greetingStyle",
      "defaultLanguage",
      "voiceType",
      "maxCallDuration",
      "afterHoursMessage",
      "customGreeting",
      "transferNumber"
    ],
    "scenarios": [
      {
        "label": "Professional salon",
        "hint": "Standard greeting",
        "values": {
          "businessName": "Luxe Beauty Studio",
          "receptionistName": "Sarah",
          "greetingStyle": "professional",
          "defaultLanguage": "en",
          "voiceType": "female",
          "maxCallDuration": "5",
          "afterHoursMessage": "Thank you for calling Luxe Beauty Studio. We are currently closed. Our hours are Monday to Saturday, 9 AM to 7 PM.",
          "customGreeting": "Thank you for calling Luxe Beauty Studio, how may I help you today?",
          "transferNumber": "+18045550100"
        }
      },
      {
        "label": "Warm and friendly",
        "hint": "Relaxed tone",
        "values": {
          "businessName": "Serenity Salon and Spa",
          "receptionistName": "Maya",
          "greetingStyle": "friendly",
          "defaultLanguage": "en",
          "voiceType": "female",
          "maxCallDuration": "7",
          "afterHoursMessage": "Thanks for calling Serenity Salon. We are closed right now but will be back tomorrow at 9 AM.",
          "customGreeting": "Hi there, welcome to Serenity Salon and Spa! How can we help today?",
          "transferNumber": "+18045550101"
        }
      },
      {
        "label": "Bilingual clinic",
        "hint": "Spanish support",
        "values": {
          "businessName": "Central Beauty Clinic",
          "receptionistName": "Elena",
          "greetingStyle": "formal",
          "defaultLanguage": "es",
          "voiceType": "male",
          "maxCallDuration": "10",
          "afterHoursMessage": "Gracias por llamar a Central Beauty Clinic. Estamos cerrados. Nuestro horario es de lunes a sabado, 9 a 19 horas.",
          "customGreeting": "Gracias por llamar a Central Beauty Clinic. Como podemos ayudarle?",
          "transferNumber": "+18045550102"
        }
      }
    ]
  },
  "voice": {
    "key": "voice",
    "label": "Voice Receptionist",
    "description": "Take and manage live calls.",
    "fields": [
      "twilioPhoneNumber"
    ],
    "scenarios": [
      {
        "label": "Salon main line",
        "hint": "Primary number",
        "values": {
          "twilioPhoneNumber": "+18045550100"
        }
      },
      {
        "label": "Second location",
        "hint": "Branch number",
        "values": {
          "twilioPhoneNumber": "+18045550101"
        }
      }
    ]
  },
  "chat": {
    "key": "chat",
    "label": "AI Chat Assistant",
    "description": "Ask anything about your salon.",
    "fields": [
      "input"
    ],
    "scenarios": [
      {
        "label": "Today's bookings",
        "hint": "Ask about the schedule",
        "values": {
          "input": "How many appointments do I have today and are there any gaps I could fill?"
        }
      },
      {
        "label": "Revenue question",
        "hint": "Ask about performance",
        "values": {
          "input": "How did revenue compare with last week?"
        }
      },
      {
        "label": "Marketing idea",
        "hint": "Ask for a suggestion",
        "values": {
          "input": "Suggest a promotion to fill quiet weekday afternoons."
        }
      }
    ]
  },
  "sms-chat": {
    "key": "sms-chat",
    "label": "SMS Chat",
    "description": "Handle incoming text messages.",
    "fields": [
      "input"
    ],
    "scenarios": [
      {
        "label": "Booking enquiry",
        "hint": "Client asking for a slot",
        "values": {
          "input": "Do you have anything available on Saturday morning?"
        }
      },
      {
        "label": "Price question",
        "hint": "Client asking a price",
        "values": {
          "input": "How much is a cut and blow dry?"
        }
      },
      {
        "label": "Running late",
        "hint": "Client warning",
        "values": {
          "input": "I am stuck in traffic and will be about ten minutes late."
        }
      }
    ]
  },
};
