// AI Inventory Autopilot
// POST: scans products at/below reorder level and creates DRAFT PurchaseOrders.
// One PO per vendor (default vendor by name match, or first active vendor).
// All POs are saved with status='draft' so a manager must approve before sending.

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireRoles } from "@/lib/api-auth";
import { openRouterChat } from "@/lib/openrouter";
import {
  parseAIJson,
  persistAIResult,
  DEFAULT_AI_MODEL,
} from "@/lib/ai-helpers";

export async function POST(req: NextRequest) {
  const auth = await requireRoles(["OWNER", "MANAGER", "PLATFORM_ADMIN"]);
  if (auth instanceof NextResponse) return auth;
  if (!auth.businessId) {
    return NextResponse.json({ error: "no business context" }, { status: 400 });
  }

  // 1. Find products at/below reorder level
  const lowStock = await prisma.product.findMany({
    where: {
      businessId: auth.businessId,
      isActive: true,
      trackInventory: true,
      // quantityOnHand <= reorderLevel — emulate without raw SQL
    },
  });

  const candidates = lowStock.filter(
    (p) => p.quantityOnHand <= (p.reorderLevel || 0)
  );

  if (candidates.length === 0) {
    return NextResponse.json({
      ok: true,
      created: 0,
      message: "No products below reorder level.",
    });
  }

  // 2. Optionally ask LLM to RANK / annotate vendor selection notes (stays inside DB choices)
  const vendors = await prisma.vendor.findMany({
    where: { businessId: auth.businessId, isActive: true },
  });
  if (vendors.length === 0) {
    return NextResponse.json(
      { error: "No active vendors. Create one first." },
      { status: 412 }
    );
  }

  const aiPrompt = `Choose the best vendor for each low-stock product. Vendors: ${JSON.stringify(
    vendors.map((v) => ({ id: v.id, name: v.name, terms: v.paymentTerms }))
  )}. Products: ${JSON.stringify(
    candidates.map((p) => ({
      id: p.id,
      name: p.name,
      brand: p.brand,
      sku: p.sku,
    }))
  )}.

Return JSON: { "assignments": [{ "productId": "...", "vendorId": "...", "rationale": "..." }] }`;

  let assignments: Array<{ productId: string; vendorId: string; rationale: string }> = [];
  try {
    const ai = await openRouterChat(
      [
        {
          role: "system",
          content: "You are a salon procurement assistant. Be concise.",
        },
        { role: "user", content: aiPrompt },
      ],
      { temperature: 0.3, maxTokens: 1500 }
    );
    const parsed = parseAIJson<any>(ai);
    if (parsed?.assignments) assignments = parsed.assignments;
  } catch {
    // Fall back to round-robin assignment.
  }

  if (assignments.length === 0) {
    assignments = candidates.map((p, i) => ({
      productId: p.id,
      vendorId: vendors[i % vendors.length].id,
      rationale: "Auto-assigned by round-robin (LLM unavailable).",
    }));
  }

  // 3. Group by vendor and create one DRAFT PO each.
  const grouped = new Map<string, typeof assignments>();
  for (const a of assignments) {
    if (!grouped.has(a.vendorId)) grouped.set(a.vendorId, []);
    grouped.get(a.vendorId)!.push(a);
  }

  const createdPOs: any[] = [];
  for (const [vendorId, items] of grouped.entries()) {
    const productMap = new Map(candidates.map((c) => [c.id, c]));
    const itemRows = items
      .map((it) => {
        const p = productMap.get(it.productId);
        if (!p) return null;
        const qty = Math.max(p.reorderQuantity || 1, 1);
        const cost = Number(p.cost || 0);
        return {
          productId: p.id,
          productName: p.name,
          sku: p.sku || null,
          quantityOrdered: qty,
          unitCost: cost,
          totalCost: cost * qty,
        };
      })
      .filter(Boolean) as any[];

    const subtotal = itemRows.reduce((s, r) => s + Number(r.totalCost), 0);
    const poNumber = `AI-${Date.now()}-${vendorId.slice(-4)}`;

    const po = await prisma.purchaseOrder.create({
      data: {
        poNumber,
        vendorId,
        createdById: auth.id,
        status: "draft",
        subtotal,
        taxAmount: 0,
        shippingAmount: 0,
        totalAmount: subtotal,
        notes: "Auto-generated by AI Inventory Autopilot. Review before sending.",
        items: { create: itemRows },
      },
    });
    createdPOs.push({ id: po.id, poNumber: po.poNumber, items: itemRows.length });
  }

  persistAIResult({
    businessId: auth.businessId,
    userId: auth.id,
    feature: "inventory_autopilot",
    input: { lowStockCount: candidates.length },
    output: { createdPOs, assignments },
    model: DEFAULT_AI_MODEL,
  });

  return NextResponse.json({
    ok: true,
    created: createdPOs.length,
    purchaseOrders: createdPOs,
  });
}
